### ISSUE TITLE
Test by mocking http request

### ISSUE THREAD

**Issue by vohoanglong0107** [rust-lang/bors#93]
Since this is a significant change, I think it's worth outlining my plan here.

To move from mocking dependencies with trait to using a http request mocking framework like wiremock, the http mock must support mocking both the Github API and Team API for resolving permissions.

For Github API, the mock must include the following endpoints:
- [x] GET `/app` -- checking if a comment belong to bors or a normal github user.
- [x] GET `/app/installations` and GET `/installation/repositories` -- used for listing all repositories managed by bors.
- [x] POST `/app/installations/{...}/access_tokens` -- used by `octocrab` to perform authentication, requires a dummy private key.
- [x] GET `/repos/{owner}/{name}/pulls/{number}` -- used to get informations for a pull requests, like head SHA.
- [x] POST `/repos/{owner}/{name}/issues/{number}/comments` -- used to post a new comment.
- [x] POST `/repos/{owner}/{name}/issues/{number}/labels` -- used to attach a label to an issue.
- [x] DELETE `/repos/{owner}/{name}/issues/{number}/labels/{name}` -- used to delete a label from an issue.
- [x] GET `/repos/{owner}/{name}/branches/{name}` -- used to get informations for a branch, like head SHA.
- [x] POST `/repos/{owner}/{name}/git/refs` -- used to create a new branch.
- [x] PATCH `/repos/{owner}/{name}/git/refs/heads/{branch_name}` -- used to update head of a branch.
- [x] POST `/repos/{owner}/{name}/merges` -- used to merge branches.
- [x] GET `/repos/{owner}/{name}/commits/{sha}/check-suites` -- used to get check suites for a commit.
- [x] POST `/repos/{owner}/{name}/actions/runs/{run_id}/cancel` -- used to cancel a github action workflow.
- [x] GET `/repos/{owner}/{name}/contents/rust-bors.toml` -- used to get bors config.

For Team API, the mock must include this endpoint: GET `/v1/permission/bors.{name}.{permission}.json`.

To implement this, I propose we create a `BorsTester` struct that facilitates the creation of the mock server, along with multiple queues used for events handling. This struct will also keep an in memory version github server, which will track all of the changes made through Github API.

@Kobzol Would love to hear your feedback on this.

**Comment by Kobzol** [comment]
Wow, that's a lot of endpoints. But I still think it will be worth it. Yeah, this is a good plan, I'd just like to review it in smaller PRs, and not one big change xD

There are a few things that we need to be able to do in an end-to-end test:
1) Initialize the app (this will need to read from a bunch of endpoints, including the team permissions).
2) Send a webhook to the app.
3) Read a comment from a PR.
4) (many others, for later)

So I would go step by step, and start with just step 1). Have a way of initializing the app, so that it can resolve the Bors config from a repo, read the installed repos for the given installation, and read the teams permissions. That should be more than enough for a single PR.
